## Scraping the Whole Page!

In [1]:
import selenium
# import pyttsx3
from selenium import webdriver
import time
import os
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.action_chains import ActionChains
# import speech_recognition as sr
import pyautogui
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from bs4 import BeautifulSoup
from collections import defaultdict

In [2]:
options = Options()
options.add_argument("start-maximized")
options.add_argument("--disable-extensions")

options.add_experimental_option("prefs", { \
"profile.default_content_setting_values.media_stream_mic": 1,
"profile.default_content_setting_values.media_stream_camera": 1,
"profile.default_content_setting_values.geolocation": 1,
"profile.default_content_setting_values.notifications": 1
})

In [3]:
def getprojectinfo(reflist):   
    
    
    driver = webdriver.Chrome(options=options,
                                  executable_path=ChromeDriverManager().install())

    information = defaultdict(list)

        # opening mahaonline webiee!

    driver.get("https://maharerait.mahaonline.gov.in/SearchList/Search")
    time.sleep(2)

        # clicking on the projectdetails

    driver.find_element_by_xpath('//*[@id="TheForm"]/div[1]/div[3]/div/div/div[2]/div[2]/a').click()
    time.sleep(2)

        ## click on registered projects

    driver.find_element_by_xpath('//*[@id="Agent"]').click()
    time.sleep(2)


        ## clicking on Advance button

    driver.find_element_by_xpath('//*[@id="btnAdvance"]').click()
    time.sleep(2)


        ## selecting element as Maharastra

    driver.find_element_by_xpath('//*[@id="State"]').send_keys('MAHARASTRA')
    time.sleep(2)


        ## Selecting the city as Mumbai 

    driver.find_element_by_xpath('//*[@id="District"]').send_keys('Mumbai City')
    time.sleep(2)


        # Click on the search

    driver.find_element_by_xpath('//*[@id="btnSearch"]').click()

    time.sleep(2)

    details = []
    
    window_before = driver.window_handles[0]

    for col in range(4):

            for i in range(0,len(reflist)):

                widow_before = driver.window_handles[0]

                driver.find_element_by_xpath(reflist[i]).click()

                time.sleep(1)


                current_tab=driver.window_handles[1]

                driver.switch_to.window(current_tab)


                try:

                    table = driver.find_element_by_xpath('//*[@id="DataGrid"]/div/div/table').text
                    table = table.split('\n')
                    tabcols = table[:-1]
                    tabdetails = table[-1]
                    tabdetails = tabdetails.split(' ')
                    details.append(tabdetails)




                except:

                     details.append(' ')


                driver.close()
                driver.switch_to_window(window_before)
                
                
    return details
  

# driver.switch_to_window(window_before)

# driver.switch_to_window(window_before)
# driver.find_element_by_xpath('//*[@id="btnNext"]').click()
# time.sleep(1)

In [4]:
reflisttcreate = ['//*[@id="gridview"]/div[1]/div/table/tbody/tr['+str(int(i))+']'+'/td[4]/b/a' for i in range(1,51)]

reflisttcreate

In [5]:
details = getprojectinfo(reflisttcreate)

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 91.0.4472
[WDM] - Get LATEST driver version for 91.0.4472

[WDM] - Driver [C:\Users\meet\.wdm\drivers\chromedriver\win32\91.0.4472.19\chromedriver.exe] found in cache
<ipython-input-3-84d0cf3d6b86>:87: DeprecationWarning: use driver.switch_to.window instead
  driver.switch_to_window(window_before)

In [6]:
details

[['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 ' ',
 ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 ' ',
 ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 ' ',
 ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 ' ',
 ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 ' ',
 ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 ['5', 'Lodha', 'New', 'Cuffe', 'Parade', 'Residential', 'Abhishek', 'Lodha'],
 ['3', 'ROHAN', 'LIFESCAPES', 'MIRAGE', 'Residential', 'ROHAN', 'LIFESCAPES'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ' ',
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ' ',
 ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 ['1', 'NIL', 'Others', 'NIL'],
 ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 ' ',
 ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 ' ',
 ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 ' ',
 ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 ' ',
 ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 ' ',
 ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 ' ',
 ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 ' ',
 ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 ['5', 'Lodha', 'New', 'Cuffe', 'Parade', 'Residential', 'Abhishek', 'Lodha'],
 ['3', 'ROHAN', 'LIFESCAPES', 'MIRAGE', 'Residential', 'ROHAN', 'LIFESCAPES'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ' ',
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ' ',
 ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 ['1', 'NIL', 'Others', 'NIL'],
 ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 ' ',
 ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 ' ',
 ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 ' ',
 ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 ' ',
 ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 ' ',
 ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 ' ',
 ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 ' ',
 ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 ['5', 'Lodha', 'New', 'Cuffe', 'Parade', 'Residential', 'Abhishek', 'Lodha'],
 ['3', 'ROHAN', 'LIFESCAPES', 'MIRAGE', 'Residential', 'ROHAN', 'LIFESCAPES'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ' ',
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ' ',
 ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 ['1', 'NIL', 'Others', 'NIL'],
 ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 ' ',
 ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 ' ',
 ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 ' ',
 ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 ' ',
 ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 ' ',
 ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 ' ',
 ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 ' ',
 ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 ['5', 'Lodha', 'New', 'Cuffe', 'Parade', 'Residential', 'Abhishek', 'Lodha'],
 ['3', 'ROHAN', 'LIFESCAPES', 'MIRAGE', 'Residential', 'ROHAN', 'LIFESCAPES'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ' ',
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 ' ',
 ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 ['1', 'NIL', 'Others', 'NIL'],
 ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 ' ',
 ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 ' ']

In [7]:
len(details)

200

In [8]:
details_map = {i+1:details[i] for i in range(len(details))}
details_map

{1: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 2: ' ',
 3: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 4: ' ',
 5: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 6: ' ',
 7: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 8: ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 9: ' ',
 10: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 11: ' ',
 12: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 13: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 14: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 15: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 16: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 17: ' ',
 18: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 19: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 20: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 21: ' ',
 22: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 23: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 24: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 25: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 26: ['1', 'NIL', 'Others', 'NIL'],
 27: ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 28: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 29: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 30: ' ',
 31: ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 32: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 33: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 34: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 35: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 36: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 37: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 38: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 39: ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 40: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 41: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 42: ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 43: ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 44: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 45: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 46: ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 47: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 48: ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 49: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 50: ' ',
 51: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 52: ' ',
 53: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 54: ' ',
 55: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 56: ' ',
 57: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 58: ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 59: ' ',
 60: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 61: ' ',
 62: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 63: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 64: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 65: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 66: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 67: ' ',
 68: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 69: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 70: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 71: ' ',
 72: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 73: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 74: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 75: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 76: ['1', 'NIL', 'Others', 'NIL'],
 77: ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 78: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 79: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 80: ' ',
 81: ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 82: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 83: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 84: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 85: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 86: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 87: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 88: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 89: ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 90: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 91: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 92: ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 93: ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 94: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 95: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 96: ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 97: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 98: ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 99: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 100: ' ',
 101: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 102: ' ',
 103: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 104: ' ',
 105: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 106: ' ',
 107: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 108: ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 109: ' ',
 110: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 111: ' ',
 112: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 113: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 114: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 115: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 116: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 117: ' ',
 118: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 119: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 120: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 121: ' ',
 122: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 123: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 124: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 125: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 126: ['1', 'NIL', 'Others', 'NIL'],
 127: ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 128: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 129: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 130: ' ',
 131: ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 132: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 133: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 134: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 135: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 136: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 137: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 138: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 139: ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 140: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 141: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 142: ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 143: ['4',
  'LA',
  'MAGAZINE',
  'BY',
  'OPTIONS',
  'Commercial',
  'GIRISH',
  'PATEL'],
 144: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 145: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 146: ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 147: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 148: ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 149: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 150: ' ',
 151: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 152: ' ',
 153: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 154: ' ',
 155: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 156: ' ',
 157: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 158: ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 159: ' ',
 160: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 161: ' ',
 162: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 163: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 164: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 165: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 166: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 167: ' ',
 168: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 169: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 170: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 171: ' ',
 172: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 173: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 174: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 175: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 176: ['1', 'NIL', 'Others', 'NIL'],
 177: ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 178: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 179: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 180: ' ',
 181: ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 182: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 183: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 184: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 185: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 186: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 187: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 188: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 189: ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 190: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 191: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 192: ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 193: ['4',
  'LA',
  'MAGAZINE',
  'BY',
  'OPTIONS',
  'Commercial',
  'GIRISH',
  'PATEL'],
 194: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 195: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 196: ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 197: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 198: ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 199: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 200: ' '}

In [9]:
details_map_temp = details_map

In [10]:
for key,val in details_map_temp.items():
    if val==' ':
        details_map_temp[key] = ['na']*6

In [11]:
details_map_temp

{1: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 2: ['na', 'na', 'na', 'na', 'na', 'na'],
 3: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 4: ['na', 'na', 'na', 'na', 'na', 'na'],
 5: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 6: ['na', 'na', 'na', 'na', 'na', 'na'],
 7: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 8: ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 9: ['na', 'na', 'na', 'na', 'na', 'na'],
 10: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 11: ['na', 'na', 'na', 'na', 'na', 'na'],
 12: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 13: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 14: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 15: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 16: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 17: ['na', 'na', 'na', 'na', 'na', 'na'],
 18: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 19: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 20: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 21: ['na', 'na', 'na', 'na', 'na', 'na'],
 22: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 23: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 24: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 25: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 26: ['1', 'NIL', 'Others', 'NIL'],
 27: ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 28: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 29: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 30: ['na', 'na', 'na', 'na', 'na', 'na'],
 31: ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 32: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 33: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 34: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 35: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 36: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 37: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 38: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 39: ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 40: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 41: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 42: ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 43: ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 44: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 45: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 46: ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 47: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 48: ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 49: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 50: ['na', 'na', 'na', 'na', 'na', 'na'],
 51: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 52: ['na', 'na', 'na', 'na', 'na', 'na'],
 53: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 54: ['na', 'na', 'na', 'na', 'na', 'na'],
 55: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 56: ['na', 'na', 'na', 'na', 'na', 'na'],
 57: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 58: ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 59: ['na', 'na', 'na', 'na', 'na', 'na'],
 60: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 61: ['na', 'na', 'na', 'na', 'na', 'na'],
 62: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 63: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 64: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 65: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 66: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 67: ['na', 'na', 'na', 'na', 'na', 'na'],
 68: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 69: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 70: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 71: ['na', 'na', 'na', 'na', 'na', 'na'],
 72: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 73: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 74: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 75: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 76: ['1', 'NIL', 'Others', 'NIL'],
 77: ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 78: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 79: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 80: ['na', 'na', 'na', 'na', 'na', 'na'],
 81: ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 82: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 83: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 84: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 85: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 86: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 87: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 88: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 89: ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 90: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 91: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 92: ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 93: ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 94: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 95: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 96: ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 97: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 98: ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 99: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 100: ['na', 'na', 'na', 'na', 'na', 'na'],
 101: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 102: ['na', 'na', 'na', 'na', 'na', 'na'],
 103: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 104: ['na', 'na', 'na', 'na', 'na', 'na'],
 105: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 106: ['na', 'na', 'na', 'na', 'na', 'na'],
 107: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 108: ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 109: ['na', 'na', 'na', 'na', 'na', 'na'],
 110: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 111: ['na', 'na', 'na', 'na', 'na', 'na'],
 112: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 113: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 114: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 115: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 116: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 117: ['na', 'na', 'na', 'na', 'na', 'na'],
 118: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 119: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 120: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 121: ['na', 'na', 'na', 'na', 'na', 'na'],
 122: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 123: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 124: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 125: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 126: ['1', 'NIL', 'Others', 'NIL'],
 127: ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 128: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 129: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 130: ['na', 'na', 'na', 'na', 'na', 'na'],
 131: ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 132: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 133: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 134: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 135: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 136: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 137: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 138: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 139: ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 140: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 141: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 142: ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 143: ['4',
  'LA',
  'MAGAZINE',
  'BY',
  'OPTIONS',
  'Commercial',
  'GIRISH',
  'PATEL'],
 144: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 145: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 146: ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 147: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 148: ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 149: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 150: ['na', 'na', 'na', 'na', 'na', 'na'],
 151: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 152: ['na', 'na', 'na', 'na', 'na', 'na'],
 153: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 154: ['na', 'na', 'na', 'na', 'na', 'na'],
 155: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 156: ['na', 'na', 'na', 'na', 'na', 'na'],
 157: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 158: ['2', 'RUPAREL', 'ARIANA', 'Residential', 'RUPAREL'],
 159: ['na', 'na', 'na', 'na', 'na', 'na'],
 160: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 161: ['na', 'na', 'na', 'na', 'na', 'na'],
 162: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 163: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 164: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 165: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 166: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 167: ['na', 'na', 'na', 'na', 'na', 'na'],
 168: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 169: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 170: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 171: ['na', 'na', 'na', 'na', 'na', 'na'],
 172: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 173: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 174: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 175: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 176: ['1', 'NIL', 'Others', 'NIL'],
 177: ['1', 'LODHA', 'PARK', 'Residential', 'LODHA'],
 178: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 179: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 180: ['na', 'na', 'na', 'na', 'na', 'na'],
 181: ['1', 'MAHADA', 'Residential', 'MAHARASHTRA', 'GOVERMENT'],
 182: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 183: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 184: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 185: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 186: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 187: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 188: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 189: ['7', 'Platinum', 'Residential', 'Shraddha', 'Estate'],
 190: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 191: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 192: ['4', 'Sparkle', 'Residential', 'Kalpataru'],
 193: ['4',
  'LA',
  'MAGAZINE',
  'BY',
  'OPTIONS',
  'Commercial',
  'GIRISH',
  'PATEL'],
 194: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 195: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 196: ['1', 'INSIGNIA', 'Residential', 'DHEERAJ', 'REALTY'],
 197: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 198: ['2', 'Greenfields', 'Residential', 'Kalpesh', 'Patel'],
 199: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 200: ['na', 'na', 'na', 'na', 'na', 'na']}

extra = {}
for key,val in details_map_temp.items():
    if len(val)>6:
        extra[key] = val
        
extra

In [68]:
extra1 = {}
for key,val in details_map_temp.items():
    if len(val)==6:
        extra1[key] = val
        
extra1

{1: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 2: ['na', 'na', 'na', 'na', 'na', 'na'],
 3: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 4: ['na', 'na', 'na', 'na', 'na', 'na'],
 6: ['na', 'na', 'na', 'na', 'na', 'na'],
 7: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 9: ['na', 'na', 'na', 'na', 'na', 'na'],
 11: ['na', 'na', 'na', 'na', 'na', 'na'],
 12: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 15: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 16: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 17: ['na', 'na', 'na', 'na', 'na', 'na'],
 18: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 19: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 20: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 21: ['na', 'na', 'na', 'na', 'na', 'na'],
 22: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 24: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 28: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 30: ['na', 'na', 'na', 'na', 'na', 'na'],
 50: ['na', 'na', 'na', 'na', 'na', 'na'],
 51: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 52: ['na', 'na', 'na', 'na', 'na', 'na'],
 53: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 54: ['na', 'na', 'na', 'na', 'na', 'na'],
 56: ['na', 'na', 'na', 'na', 'na', 'na'],
 57: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 59: ['na', 'na', 'na', 'na', 'na', 'na'],
 61: ['na', 'na', 'na', 'na', 'na', 'na'],
 62: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 65: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 66: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 67: ['na', 'na', 'na', 'na', 'na', 'na'],
 68: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 69: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 70: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 71: ['na', 'na', 'na', 'na', 'na', 'na'],
 72: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 74: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 78: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 80: ['na', 'na', 'na', 'na', 'na', 'na'],
 100: ['na', 'na', 'na', 'na', 'na', 'na'],
 101: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 102: ['na', 'na', 'na', 'na', 'na', 'na'],
 103: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 104: ['na', 'na', 'na', 'na', 'na', 'na'],
 106: ['na', 'na', 'na', 'na', 'na', 'na'],
 107: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 109: ['na', 'na', 'na', 'na', 'na', 'na'],
 111: ['na', 'na', 'na', 'na', 'na', 'na'],
 112: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 115: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 116: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 117: ['na', 'na', 'na', 'na', 'na', 'na'],
 118: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 119: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 120: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 121: ['na', 'na', 'na', 'na', 'na', 'na'],
 122: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 124: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 128: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 130: ['na', 'na', 'na', 'na', 'na', 'na'],
 150: ['na', 'na', 'na', 'na', 'na', 'na'],
 151: ['1', 'OBEROI', 'EXQUISITE', 'Residential', 'OBEROI', 'REALTY'],
 152: ['na', 'na', 'na', 'na', 'na', 'na'],
 153: ['2', 'Raj', 'Shivganga', 'Residential', 'Basant', 'Sethia'],
 154: ['na', 'na', 'na', 'na', 'na', 'na'],
 156: ['na', 'na', 'na', 'na', 'na', 'na'],
 157: ['1', 'JATIA', 'HOUSE', 'Residential', 'JATIA', 'BUILDERS'],
 159: ['na', 'na', 'na', 'na', 'na', 'na'],
 161: ['na', 'na', 'na', 'na', 'na', 'na'],
 162: ['3', 'LODHA', 'PALAWA', 'Residential', 'AJAY', 'SINGH'],
 165: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 166: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 167: ['na', 'na', 'na', 'na', 'na', 'na'],
 168: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 169: ['2', 'Solitare', 'Estates', 'Residential', 'Solitarian', 'Developers'],
 170: ['2', 'HARBOUR', 'HEIGHTS', 'Commercial', 'RAHUL', 'SHAH'],
 171: ['na', 'na', 'na', 'na', 'na', 'na'],
 172: ['1', 'ASHOKA', 'DEVELOPERS', 'Residential', 'ROSHAN', 'AGARWAL'],
 174: ['1', 'Sisodiya', 'investment', 'Residential', 'Pukhraj', 'Bafna'],
 178: ['5', 'Imperial', 'Heights', 'Residential', 'Radius', 'Developers'],
 180: ['na', 'na', 'na', 'na', 'na', 'na'],
 200: ['na', 'na', 'na', 'na', 'na', 'na']}

In [69]:
import pandas as pd
import numpy as np

In [70]:
detailsdict = pd.DataFrame.from_dict(extra1)
detailsdict = detailsdict.T
detailsdict.head(2)

    0       1          2            3       4       5
1   1  OBEROI  EXQUISITE  Residential  OBEROI  REALTY
2  na      na         na           na      na      na

In [71]:
col1 = list(detailsdict[1].values)
col2 = list(detailsdict[2].values)
finalval = []
for i,j in zip(col1,col2):
    if i=='na' or j=='na':
        finalval.append('na')
    else:
        finalval.append(i+' '+j)

In [72]:
detailsdict['Project Name'] = np.array(finalval)
detailsdict.head()

    0       1          2            3       4       5      Project Name
1   1  OBEROI  EXQUISITE  Residential  OBEROI  REALTY  OBEROI EXQUISITE
2  na      na         na           na      na      na                na
3   2     Raj  Shivganga  Residential  Basant  Sethia     Raj Shivganga
4  na      na         na           na      na      na                na
6  na      na         na           na      na      na                na

In [55]:
col1 = list(detailsdict[4].values)
col2 = list(detailsdict[5].values)
finalval = []
for i,j in zip(col1,col2):
    if i=='na' or j=='na':
        finalval.append('na')
    else:
        finalval.append(i+' '+j)

In [73]:
detailsdict['Promoter Name'] = np.array(finalval)
detailsdict.head()

,0,1,2,3,4,5,Project Name,Promoter Name
1,1,OBEROI,EXQUISITE,Residential,OBEROI,REALTY,OBEROI EXQUISITE,OBEROI EXQUISITE
2,na,na,na,na,na,na,na,na
3,2,Raj,Shivganga,Residential,Basant,Sethia,Raj Shivganga,Raj Shivganga
4,na,na,na,na,na,na,na,na
6,na,na,na,na,na,na,na,na

In [74]:
detailsdict.columns

Index([0, 1, 2, 3, 4, 5, 'Project Name', 'Promoter Name'], dtype='object')

In [75]:
detailsdict = detailsdict[[0,'Project Name', 3,'Promoter Name']]
detailsdict.head(2)

    0      Project Name            3     Promoter Name
1   1  OBEROI EXQUISITE  Residential  OBEROI EXQUISITE
2  na                na           na                na

In [76]:
detailsdict.columns = ['srno','Project Name','Project Type','Promoter Name']
detailsdict

    srno         Project Name Project Type        Promoter Name
1      1     OBEROI EXQUISITE  Residential     OBEROI EXQUISITE
2     na                   na           na                   na
3      2        Raj Shivganga  Residential        Raj Shivganga
4     na                   na           na                   na
6     na                   na           na                   na
..   ...                  ...          ...                  ...
172    1    ASHOKA DEVELOPERS  Residential    ASHOKA DEVELOPERS
174    1  Sisodiya investment  Residential  Sisodiya investment
178    5     Imperial Heights  Residential     Imperial Heights
180   na                   na           na                   na
200   na                   na           na                   na

[84 rows x 4 columns]

In [24]:
tempo = details_map_temp
a = {}
for key,val in tempo.items():
    if len(val)>6:
        a[key] = val
        
print(len(a))

84

In [26]:
a

{5: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 10: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 13: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 14: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 23: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 25: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 29: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 32: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 33: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 34: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 35: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 36: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 37: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 38: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 40: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 41: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 43: ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 44: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 45: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 47: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 49: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 55: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 60: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 63: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 64: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 73: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 75: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 79: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 82: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 83: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 84: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 85: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 86: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 87: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 88: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 90: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 91: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 93: ['4', 'LA', 'MAGAZINE', 'BY', 'OPTIONS', 'Commercial', 'GIRISH', 'PATEL'],
 94: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 95: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 97: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 99: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 105: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 110: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 113: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 114: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 123: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 125: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 129: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 132: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 133: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 134: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 135: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 136: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 137: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 138: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 140: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 141: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 143: ['4',
  'LA',
  'MAGAZINE',
  'BY',
  'OPTIONS',
  'Commercial',
  'GIRISH',
  'PATEL'],
 144: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 145: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 147: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 149: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 155: ['1',
  'TRISON',
  'BUILDERS,',
  'RELIANCE',
  'ESTAE',
  'DEVELOPERS,THIM',
  'CONST',
  'PVT',
  'LTD',
  'ETC',
  'Residential',
  'Mr',
  'SYDNEY',
  'LOBO,',
  'MR',
  'HEMENDRA',
  'MAHAPRA,',
  'MR',
  'ANWAR',
  'HUSSAIN',
  'ETC'],
 160: ['1',
  'Main',
  'Office',
  '02229659720',
  '413',
  'Autumn',
  'Gruve',
  'Drive,',
  'Lokhandwala',
  'Township,',
  'Akurli',
  'Road,',
  'Kandivali',
  'East,',
  'Mumbai',
  '400101',
  'kagarwal@bestindiaproperties.com',
  'View'],
 163: ['5',
  'Lodha',
  'New',
  'Cuffe',
  'Parade',
  'Residential',
  'Abhishek',
  'Lodha'],
 164: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 173: ['7',
  'One',
  'Avighna',
  'Park',
  'Residential',
  'Nish',
  'Developers',
  'Pvt',
  'Ltd'],
 175: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 179: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 182: ['1',
  'Vishakha',
  'Exports',
  '02222657524',
  '63',
  'Bombay',
  'Mutual',
  'Bldg',
  '1st',
  'flr',
  '28',
  'Sir',
  'P',
  'M',
  'Road',
  'Fort',
  'Mumbai',
  '400001',
  'valiaparesh@gmail.com',
  '02222651334',
  'View'],
 183: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 184: ['4',
  'WESTERN',
  'EDGE',
  'II',
  'Commercial',
  'KANAKIA',
  'SPACES',
  'PVT',
  'LTD'],
 185: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 186: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 187: ['1',
  'Mansukh',
  'D',
  'Gala',
  '02225680073',
  'B/20',
  'shiv',
  'krupa',
  'devidayal',
  'rd',
  'mulund',
  'west',
  'mansukhd58@gmail.com',
  'View'],
 188: ['2',
  'SALSETTE',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 190: ['1',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD',
  'Commercial',
  'ZENITH',
  'TINS',
  'PVT',
  'LTD'],
 191: ['3',
  'CELESTIA',
  'SPACES',
  'BY',
  'PENINSULA',
  'LAND',
  'Residential',
  'ASHOK',
  'PIRAMAL'],
 193: ['4',
  'LA',
  'MAGAZINE',
  'BY',
  'OPTIONS',
  'Commercial',
  'GIRISH',
  'PATEL'],
 194: ['2',
  'SOLITAIRE',
  'PARADISE',
  'Residential',
  'MAHAVEER',
  'BUILDERS',
  'AND',
  'DEVELOPERS'],
 195: ['3', 'RADIUS', '-', '7', 'HUGES', 'Residential', 'SANJAY', 'CHABBRIA'],
 197: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 199: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD']}

In [29]:
size_map = {len(val) for key,val in tempo.items() if len(val)>6}

In [30]:
size_map

{7, 8, 9, 10, 14, 18, 21}

In [77]:
tempo = details_map_temp
a = {}
for key,val in tempo.items():
    if len(val)==7:
        a[key] = val

In [78]:
a

{14: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 25: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 29: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 33: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 35: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 36: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 47: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 49: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 64: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 75: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 79: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 83: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 85: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 86: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 97: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 99: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 114: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 125: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 129: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 133: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 135: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 136: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 147: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 149: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD'],
 164: ['3',
  'ROHAN',
  'LIFESCAPES',
  'MIRAGE',
  'Residential',
  'ROHAN',
  'LIFESCAPES'],
 175: ['1', 'Dreams', 'The', 'Mall', 'Commercial', 'Satra', 'Property'],
 179: ['1', 'NEW', 'CUFFE', 'PARADE', 'Residential', 'LODHA', 'GROUP'],
 183: ['25', 'Ashok', 'Gardens', 'Residential', 'Swan', 'Energy', 'LTD'],
 185: ['4', 'OBEROI', 'SKY', 'CITY', 'Residential', 'OBEROI', 'REALTY'],
 186: ['2', 'ONE', 'AVIGHNA', 'PARK', 'Residential', 'NISHANT', 'AGARWAL'],
 197: ['2', 'The', 'Hive,', 'Satya', 'Commercial', 'Manish', 'Agarwal'],
 199: ['2', 'CELISTIA', 'SPACES', 'Residential', 'PENENSULA', 'PVT', 'LTD']}

In [79]:
df_7 = pd.DataFrame.from_dict(a)
df_7 = df_7.T
df_7

      0         1           2            3            4        5           6
14    3     ROHAN  LIFESCAPES       MIRAGE  Residential    ROHAN  LIFESCAPES
25    1    Dreams         The         Mall   Commercial    Satra    Property
29    1       NEW       CUFFE       PARADE  Residential    LODHA       GROUP
33   25     Ashok     Gardens  Residential         Swan   Energy         LTD
35    4    OBEROI         SKY         CITY  Residential   OBEROI      REALTY
36    2       ONE     AVIGHNA         PARK  Residential  NISHANT     AGARWAL
47    2       The       Hive,        Satya   Commercial   Manish     Agarwal
49    2  CELISTIA      SPACES  Residential    PENENSULA      PVT         LTD
64    3     ROHAN  LIFESCAPES       MIRAGE  Residential    ROHAN  LIFESCAPES
75    1    Dreams         The         Mall   Commercial    Satra    Property
79    1       NEW       CUFFE       PARADE  Residential    LODHA       GROUP
83   25     Ashok     Gardens  Residential         Swan   Energy         LTD
85    4    OBEROI         SKY         CITY  Residential   OBEROI      REALTY
86    2       ONE     AVIGHNA         PARK  Residential  NISHANT     AGARWAL
97    2       The       Hive,        Satya   Commercial   Manish     Agarwal
99    2  CELISTIA      SPACES  Residential    PENENSULA      PVT         LTD
114   3     ROHAN  LIFESCAPES       MIRAGE  Residential    ROHAN  LIFESCAPES
125   1    Dreams         The         Mall   Commercial    Satra    Property
129   1       NEW       CUFFE       PARADE  Residential    LODHA       GROUP
133  25     Ashok     Gardens  Residential         Swan   Energy         LTD
135   4    OBEROI         SKY         CITY  Residential   OBEROI      REALTY
136   2       ONE     AVIGHNA         PARK  Residential  NISHANT     AGARWAL
147   2       The       Hive,        Satya   Commercial   Manish     Agarwal
149   2  CELISTIA      SPACES  Residential    PENENSULA      PVT         LTD
164   3     ROHAN  LIFESCAPES       MIRAGE  Residential    ROHAN  LIFESCAPES
175   1    Dreams         The         Mall   Commercial    Satra    Property
179   1       NEW       CUFFE       PARADE  Residential    LODHA       GROUP
183  25     Ashok     Gardens  Residential         Swan   Energy         LTD
185   4    OBEROI         SKY         CITY  Residential   OBEROI      REALTY
186   2       ONE     AVIGHNA         PARK  Residential  NISHANT     AGARWAL
197   2       The       Hive,        Satya   Commercial   Manish     Agarwal
199   2  CELISTIA      SPACES  Residential    PENENSULA      PVT         LTD

In [80]:
col1 = list(df_7[1].values)
col2 = list(df_7[2].values)
col3 = list(df_7[4].values)
projectname = []
for i,j,k in zip(col1,col2,col3):
    projectname.append(i+j+k)
    
col4 = list(df_7[5].values)
col5 = list(df_7[6].values)
agentname = []
for i,j in zip(col4,col5):
    agentname.append(i+j)
    

col3 = list(df_7[3].values)
details_new = pd.DataFrame()
details_new['Project Name'] = projectname
details_new['Project Agent'] = agentname
details_new['Project Type'] = col3
details_new['Srno'] = list(df_7[0].values)
details_new

                  Project Name    Project Agent Project Type Srno
0   ROHANLIFESCAPESResidential  ROHANLIFESCAPES       MIRAGE    3
1          DreamsTheCommercial    SatraProperty         Mall    1
2          NEWCUFFEResidential       LODHAGROUP       PARADE    1
3             AshokGardensSwan        EnergyLTD  Residential   25
4         OBEROISKYResidential     OBEROIREALTY         CITY    4
5        ONEAVIGHNAResidential   NISHANTAGARWAL         PARK    2
6           TheHive,Commercial    ManishAgarwal        Satya    2
7      CELISTIASPACESPENENSULA           PVTLTD  Residential    2
8   ROHANLIFESCAPESResidential  ROHANLIFESCAPES       MIRAGE    3
9          DreamsTheCommercial    SatraProperty         Mall    1
10         NEWCUFFEResidential       LODHAGROUP       PARADE    1
11            AshokGardensSwan        EnergyLTD  Residential   25
12        OBEROISKYResidential     OBEROIREALTY         CITY    4
13       ONEAVIGHNAResidential   NISHANTAGARWAL         PARK    2
14          TheHive,Commercial    ManishAgarwal        Satya    2
15     CELISTIASPACESPENENSULA           PVTLTD  Residential    2
16  ROHANLIFESCAPESResidential  ROHANLIFESCAPES       MIRAGE    3
17         DreamsTheCommercial    SatraProperty         Mall    1
18         NEWCUFFEResidential       LODHAGROUP       PARADE    1
19            AshokGardensSwan        EnergyLTD  Residential   25
20        OBEROISKYResidential     OBEROIREALTY         CITY    4
21       ONEAVIGHNAResidential   NISHANTAGARWAL         PARK    2
22          TheHive,Commercial    ManishAgarwal        Satya    2
23     CELISTIASPACESPENENSULA           PVTLTD  Residential    2
24  ROHANLIFESCAPESResidential  ROHANLIFESCAPES       MIRAGE    3
25         DreamsTheCommercial    SatraProperty         Mall    1
26         NEWCUFFEResidential       LODHAGROUP       PARADE    1
27            AshokGardensSwan        EnergyLTD  Residential   25
28        OBEROISKYResidential     OBEROIREALTY         CITY    4
29       ONEAVIGHNAResidential   NISHANTAGARWAL         PARK    2
30          TheHive,Commercial    ManishAgarwal        Satya    2
31     CELISTIASPACESPENENSULA           PVTLTD  Residential    2

In [81]:
details_new.columns

Index(['Project Name', 'Project Agent', 'Project Type', 'Srno'], dtype='object')

In [82]:
details_new = details_new[['Srno','Project Name','Project Type','Project Agent']]
details_new.head(2)

  Srno                Project Name Project Type    Project Agent
0    3  ROHANLIFESCAPESResidential       MIRAGE  ROHANLIFESCAPES
1    1         DreamsTheCommercial         Mall    SatraProperty

In [85]:
details_new.columns = ['srno','Project Name','Project Type','Promoter Name']

In [88]:
details_new.head(2)

  srno                Project Name Project Type    Promoter Name
0    3  ROHANLIFESCAPESResidential       MIRAGE  ROHANLIFESCAPES
1    1         DreamsTheCommercial         Mall    SatraProperty

In [86]:
detailsdict.head(2)

  srno      Project Name Project Type     Promoter Name
1    1  OBEROI EXQUISITE  Residential  OBEROI EXQUISITE
2   na                na           na                na

In [37]:
details_new.columns

Index(['Project Name', 'Project Agent', 'Project Type', 'Srno'], dtype='object')

In [89]:
frame_combined = pd.concat([detailsdict,details_new], ignore_index=True)
frame_combined.head(2)

  srno      Project Name Project Type     Promoter Name
0    1  OBEROI EXQUISITE  Residential  OBEROI EXQUISITE
1   na                na           na                na

In [90]:
frame_combined.shape

(116, 4)

In [91]:
frame_combined.to_csv('ProjectDetailsnew.csv',index = False)